language: java

matrix:
  include:
    - name: "Linux JDK 9"
      os: linux
      jdk: oraclejdk9
      addons:
        apt:
          packages:
            - oracle-java9-installer
      script:
        - ./config/travis/run-checks.sh
        - time travis_retry ./gradlew clean checkstyleMain checkstyleTest test systemTest

    - name: "macOSX JDK 9"
      os: osx
      script:
        - ./config/travis/run-checks.sh
        - time travis_retry ./gradlew clean checkstyleMain checkstyleTest test systemTest

    - name: "ESLint"
      language: node_js
      node_js: node
      install:
        - cd ./frontend; npm install --only=dev; cd ..'
      script:
        - npm run lint frontend/src/**/*.js
      cache:
        directories:
          - $TRAVIS_BUILD_DIR/frontend/node_modules

    - name: "Frontend Tests"
      os: linux
      dist: xenial
      addons:
        chrome: stable
      services:
        - xvfb
      before_install:
        # https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-on-travis-ci
        - sysctl kernel.unprivileged_userns_clone=1
        - sleep 3
      install:
        - cd ./frontend/tests; npm install; cd ../../
      script:
        - ./gradlew zipreport
        - ./gradlew run -Dargs="-repos https://github.com/yong24s/toolbox.git"
        - cd reposense-report
        - python -m SimpleHTTPServer 9000 > /dev/null 2>&1 & disown
        - cd ..
        - sleep 3
        - cd ./frontend/tests && npm run-script tests
        - pkill -f SimpleHTTPServer
      cache:
        directories:
          - $TRAVIS_BUILD_DIR/frontend/tests/node_modules

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
