language: java

matrix:
  include:
    - os: linux
      jdk: oraclejdk9
      script:
        - ./config/travis/run-checks.sh
        - npm run lint frontend/src/**/*.js
        - time travis_retry ./gradlew clean checkstyleMain checkstyleTest test systemTest
    - os: osx
      script:
        - ./config/travis/run-checks.sh
        - npm run lint frontend/src/**/*.js
        - time travis_retry ./gradlew clean checkstyleMain checkstyleTest test systemTest
    - os: linux
      dist: xenial
      env: FRONTEND_TEST=true
      addons:
        chrome: stable
      script: 
        - cd ./frontend/tests; npm install; cd ..
        - cd ./frontend/tests && npm run-script tests

addons:
  apt:
    packages:
      - oracle-java9-installer

before_install:
  - cd ./frontend; npm install --only=dev; cd ..

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
