language: java

matrix:
  include:
    - os: linux
      dist: xenial
      jdk: oraclejdk11
    - os: osx
      osx_image: xcode10.1

script:
  - ./config/travis/run-checks.sh
  - npm run lint frontend/src/**/*.js
  - time travis_retry ./gradlew clean checkstyleMain checkstyleTest test systemTest

before_install:
  - cd ./frontend; npm install --only=dev; cd ..

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
